server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:3307/microservices
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defalutZone: http://localhost:8761/eureka   