server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: User-Service

resilience4j:
  circuitbreaker:
    instances:
      externalAPI:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  


#management:
#  endpoints:
#    web:
#      base-path: /management         # Rename default /actuator to /management :contentReference[oaicite:1]{index=1}
#      exposure:
#        include:                     # Choose which endpoints are publicly accessible
#          - health
#          - info
#          - metrics

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defalutZone: http://localhost:8761/eureka
      